const express = require('express');
const cors = require('cors');
const bcrypt = require('bcryptjs');
const jwt = require('jsonwebtoken');
const multer = require('multer');
const XLSX = require('xlsx');
const PDFDocument = require('pdfkit');
const { stringify } = require('csv-stringify/sync');
const crypto = require('node:crypto');
const path = require('node:path');
const fs = require('node:fs');
const { query, pool } = require('./db/index.cjs');

const app = express();
const port = Number(process.env.PORT || 3000);
const root = path.join(__dirname, 'dist');
if (process.env.NODE_ENV === 'production' && !process.env.JWT_SECRET) throw new Error('JWT_SECRET é obrigatória em produção.');
const jwtSecret = process.env.JWT_SECRET || 'rv-digital-local-only';
const dataSourceSecret = crypto.createHash('sha256').update(process.env.DATA_SOURCE_SECRET || jwtSecret).digest();
const upload = multer({ storage: multer.memoryStorage(), limits: { fileSize: 10 * 1024 * 1024 } });
const pendingImports = new Map();
const types = { '.css': 'text/css', '.js': 'application/javascript', '.svg': 'image/svg+xml', '.png': 'image/png', '.jpg': 'image/jpeg', '.html': 'text/html' };
const roles = { SUPER_ADMIN: 4, MANAGER: 3, SUPERVISOR: 2, SELLER: 1 };
const defaultModuleAccess = {
	MANAGER: ['DASHBOARD','GOALS','TEAMS','INDICATORS','ACTIONS','IMPORTS','REPORTS','AUTHORIZATIONS','MESSAGES'],
	SUPERVISOR: ['DASHBOARD','TEAMS','INDICATORS','GOALS','ACTIONS','ALERTS','REPORTS','MESSAGES','AUTHORIZATIONS'],
	SELLER: ['DASHBOARD','GOALS','INDICATORS','ACTIONS','PERFORMANCE','TEAMS','REPORTS','MESSAGES']
};
const aliases = { vendedor:'seller', vendedor_nome:'seller', consultor:'seller', mesa:'team', mesa_comercial:'team', equipe:'team', cadastros_novo:'CADASTRO_NOVO', cadastro_novo:'CADASTRO_NOVO', cadastro_com_adq:'CADASTRO_ADQ', adq:'CADASTRO_ADQ', inadimplencia:'INADIMPLENCIA', volume_de_chips:'VOLUME_CHIPS', chips:'VOLUME_CHIPS', cadastro_de_evolua:'CADASTRO_EVOLUA', evolua:'CADASTRO_EVOLUA', consignado:'CONSIGNADO', pdvs_consignados:'CONSIGNADO', centuriao:'CENTURIAO', inoperancia:'INOPERANCIA', churn:'CHURN', capilaridade:'CAPILARIDADE', data:'reference_date' };

app.use(cors({ origin: process.env.APP_URL ? process.env.APP_URL.split(',') : true }));
app.use(express.json({ limit: '1mb' }));
const route = fn => (req,res,next) => Promise.resolve(fn(req,res,next)).catch(next);
const publicUser = row => ({ id:row.id, name:row.name, email:row.email, role:row.role, status:row.status, teamId:row.team_id, teamName:row.team_name });
const normalize = val => String(val ?? '').trim().normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().replace(/[^a-z0-9]+/g,'_').replace(/^_|_$/g,'');
const numeric = val => { const number=Number(String(val).replace('%','').replace(',','.')); return Number.isFinite(number) && number >= 0 ? number : null; };
const dateKey = value => value instanceof Date ? value.toISOString().slice(0,10) : String(value).slice(0,10);
const encryptSecret = value => { const iv=crypto.randomBytes(12);const cipher=crypto.createCipheriv('aes-256-gcm',dataSourceSecret,iv);const encrypted=Buffer.concat([cipher.update(value,'utf8'),cipher.final()]);return `v1.${iv.toString('hex')}.${cipher.getAuthTag().toString('hex')}.${encrypted.toString('hex')}`; };
function auth(req,res,next) { const token=req.headers.authorization?.replace('Bearer ',''); if(!token)return res.status(401).json({error:'Autenticação necessária.'}); try { req.user=jwt.verify(token,jwtSecret); next(); } catch { res.status(401).json({error:'Sessão inválida ou expirada.'}); } }
function allow(...allowed) { return (req,res,next) => allowed.includes(req.user.role) ? next() : res.status(403).json({error:'Você não tem permissão para esta ação.'}); }
const moduleRoutes = [
	['/teams',['TEAMS','ACTIONS']], ['/indicators',['INDICATORS','GOALS','ACTIONS']],
	['/goals',['GOALS','INDICATORS','PERFORMANCE']], ['/goal-change-requests',['AUTHORIZATIONS','GOALS']],
	['/actions',['ACTIONS']], ['/imports',['IMPORTS']], ['/reports',['REPORTS']], ['/conversations',['MESSAGES']]
];
async function configuredModuleAccess() { const row=(await query("SELECT value FROM settings WHERE key='module_access'")).rows[0];return row?.value||defaultModuleAccess; }
function metrics(target,achieved,direction='HIGHER_IS_BETTER') { target=Number(target); achieved=Number(achieved); const achievement=target ? (direction==='LOWER_IS_BETTER' ? (achieved<=target?100:target/Math.max(achieved,.01)*100) : achieved/target*100) : 0; return {target,achieved,difference:direction==='LOWER_IS_BETTER'?achieved-target:target-achieved,achievement:Math.max(0,achievement)}; }
async function period(id) { const data=await query(id?'SELECT * FROM periods WHERE id=$1':"SELECT * FROM periods WHERE status='OPEN' ORDER BY start_date DESC LIMIT 1",id?[id]:[]); return data.rows[0]; }
async function audit(req,action,entity,id,oldData,newData) { await query('INSERT INTO audit_logs(user_id,action,entity,entity_id,old_data,new_data,ip_address) VALUES($1,$2,$3,$4,$5,$6,$7)',[req.user?.id||null,action,entity,id||null,oldData?JSON.stringify(oldData):null,newData?JSON.stringify(newData):null,req.ip]); }
async function actionAccess(req, actionId) {
	if (roles[req.user.role] >= roles.MANAGER) return (await query('SELECT * FROM actions WHERE id=$1',[actionId])).rows[0];
	const condition=req.user.role==='SUPERVISOR'?'at.team_id=$2':'at.user_id=$2';
	return (await query(`SELECT DISTINCT a.* FROM actions a JOIN action_targets at ON at.action_id=a.id WHERE a.id=$1 AND ${condition}`,[actionId,req.user.role==='SUPERVISOR'?req.user.teamId:req.user.id])).rows[0];
}
function weightedAllocation(total, sellers) {
	const units=Math.max(0,Math.round(Number(total)));
	if(!sellers.length||!units)return sellers.map(seller=>({...seller,suggested:0}));
	const weighted=sellers.map(seller=>{const target=Number(seller.target||0);const achieved=Number(seller.achieved||0);const gap=Math.max(0,target-achieved);const capacity=Math.max(1,Number(seller.daily_capacity||0),achieved/Math.max(1,new Date().getDate()));const risk=target?Math.max(0,1-achieved/target):.5;return {...seller,weight:Math.max(.01,gap*.55+capacity*.3+risk*Math.max(target,1)*.15)};});
	const totalWeight=weighted.reduce((sum,seller)=>sum+seller.weight,0);
	const raw=weighted.map(seller=>({...seller,raw:units*seller.weight/totalWeight}));
	let remaining=units-raw.reduce((sum,seller)=>sum+Math.floor(seller.raw),0);
	const remainderOrder=[...raw].sort((a,b)=>(b.raw-Math.floor(b.raw))-(a.raw-Math.floor(a.raw)));
	const bonuses=new Map(remainderOrder.map((seller,index)=>[seller.id,index<remaining?1:0]));
	return raw.map(seller=>({...seller,suggested:Math.floor(seller.raw)+(bonuses.get(seller.id)||0)}));
}

app.use('/api',(req,res,next)=>{const match=moduleRoutes.find(([prefix])=>req.path===prefix||req.path.startsWith(`${prefix}/`));if(!match)return next();auth(req,res,route(async()=>{if(req.user.role==='SUPER_ADMIN')return next();const access=await configuredModuleAccess();return match[1].some(module=>(access[req.user.role]||[]).includes(module))?next():res.status(403).json({error:'Este módulo não está habilitado para sua função.'});}));});

app.get('/api/health',route(async(_req,res)=>{await query('SELECT 1');res.json({status:'ok',time:new Date().toISOString()});}));
app.post('/api/auth/login',route(async(req,res)=>{const {email,password}=req.body;if(!email||!password)return res.status(400).json({error:'E-mail e senha são obrigatórios.'});const data=await query('SELECT u.*,t.name team_name FROM users u LEFT JOIN teams t ON t.id=u.team_id WHERE lower(u.email)=lower($1)',[email]);const user=data.rows[0];if(!user||!(await bcrypt.compare(password,user.password_hash)))return res.status(401).json({error:'E-mail ou senha inválidos.'});if(user.status!=='ACTIVE')return res.status(403).json({error:'Este acesso está bloqueado ou inativo.'});const safe=publicUser(user);const token=jwt.sign(safe,jwtSecret,{expiresIn:'8h'});await audit({user:safe,ip:req.ip},'LOGIN','USER',user.id);res.json({token,user:safe});}));
app.get('/api/auth/me',auth,route(async(req,res)=>{const user=(await query('SELECT u.*,t.name team_name FROM users u LEFT JOIN teams t ON t.id=u.team_id WHERE u.id=$1',[req.user.id])).rows[0];res.json({user:publicUser(user)});}));
app.post('/api/auth/change-password',auth,route(async(req,res)=>{const {currentPassword,newPassword}=req.body;if(!newPassword||newPassword.length<8)return res.status(400).json({error:'A nova senha deve ter pelo menos 8 caracteres.'});const old=(await query('SELECT password_hash FROM users WHERE id=$1',[req.user.id])).rows[0];if(!(await bcrypt.compare(currentPassword||'',old.password_hash)))return res.status(400).json({error:'Senha atual inválida.'});await query('UPDATE users SET password_hash=$1,updated_at=now() WHERE id=$2',[await bcrypt.hash(newPassword,12),req.user.id]);await audit(req,'CHANGE_PASSWORD','USER',req.user.id);res.status(204).end();}));

app.get('/api/users',auth,allow('SUPER_ADMIN','MANAGER','SUPERVISOR'),route(async(req,res)=>{let where='';let params=[];if(req.user.role==='SUPERVISOR'){where='WHERE u.team_id=$1';params=[req.user.teamId];}const rows=(await query(`SELECT u.*,t.name team_name FROM users u LEFT JOIN teams t ON t.id=u.team_id ${where} ORDER BY u.name`,params)).rows;res.json({items:rows.map(publicUser)});}));
app.post('/api/users',auth,allow('SUPER_ADMIN'),route(async(req,res)=>{const {name,email,password}=req.body;let {role,teamId}=req.body;if(!name?.trim()||!email?.trim()||!password||password.length<8||!['MANAGER','SUPERVISOR','SELLER'].includes(role))return res.status(400).json({error:'Nome, e-mail, senha de 8 caracteres e função válida são obrigatórios.'});if(role==='SELLER'&&!teamId)return res.status(400).json({error:'Todo vendedor deve estar vinculado a uma mesa.'});if(role==='MANAGER')teamId=null;if(teamId&&!(await query("SELECT 1 FROM teams WHERE id=$1 AND status='ACTIVE'",[teamId])).rowCount)return res.status(400).json({error:'Mesa inválida ou inativa.'});const row=(await query('INSERT INTO users(name,email,password_hash,role,team_id) VALUES($1,$2,$3,$4,$5) RETURNING *',[name.trim(),email.trim().toLowerCase(),await bcrypt.hash(password,12),role,teamId||null])).rows[0];const item=(await query('SELECT u.*,t.name team_name FROM users u LEFT JOIN teams t ON t.id=u.team_id WHERE u.id=$1',[row.id])).rows[0];await audit(req,'CREATE','USER',row.id,null,publicUser(item));res.status(201).json({item:publicUser(item)});}));
app.patch('/api/users/:id',auth,allow('SUPER_ADMIN'),route(async(req,res)=>{const old=(await query('SELECT * FROM users WHERE id=$1',[req.params.id])).rows[0];if(!old)return res.status(404).json({error:'Usuário não encontrado.'});let {name,status,role,teamId,password}=req.body;const nextRole=role||old.role;if(!['MANAGER','SUPERVISOR','SELLER'].includes(nextRole))return res.status(400).json({error:'Função inválida.'});const nextTeam=nextRole==='MANAGER'?null:(teamId===null?null:(teamId||old.team_id));if(nextRole==='SELLER'&&!nextTeam)return res.status(400).json({error:'Todo vendedor deve permanecer vinculado a uma mesa.'});if(nextTeam&&!(await query('SELECT 1 FROM teams WHERE id=$1',[nextTeam])).rowCount)return res.status(400).json({error:'Mesa inválida.'});const passwordHash=password?(password.length>=8?await bcrypt.hash(password,12):null):null;if(password&&!passwordHash)return res.status(400).json({error:'A nova senha deve ter pelo menos 8 caracteres.'});const row=(await query('UPDATE users SET name=COALESCE($1,name),status=COALESCE($2,status),role=$3,team_id=$4,password_hash=COALESCE($5,password_hash),updated_at=now() WHERE id=$6 RETURNING *',[name?.trim()||null,status||null,nextRole,nextTeam,passwordHash,req.params.id])).rows[0];const item=(await query('SELECT u.*,t.name team_name FROM users u LEFT JOIN teams t ON t.id=u.team_id WHERE u.id=$1',[row.id])).rows[0];await audit(req,'UPDATE','USER',row.id,publicUser(old),publicUser(item));res.json({item:publicUser(item)});}));
app.delete('/api/users/:id',auth,allow('SUPER_ADMIN'),route(async(req,res)=>{const old=(await query('SELECT * FROM users WHERE id=$1',[req.params.id])).rows[0];if(!old)return res.status(404).json({error:'Usuário não encontrado.'});if(String(old.id)===String(req.user.id))return res.status(400).json({error:'Você não pode excluir o próprio acesso.'});
	const client=await pool.connect();try{await client.query('BEGIN');await client.query('UPDATE audit_logs SET user_id=null WHERE user_id=$1',[old.id]);await client.query('UPDATE action_history SET user_id=null WHERE user_id=$1',[old.id]);await client.query('UPDATE goal_change_requests SET approved_by=null WHERE approved_by=$1',[old.id]);await client.query('UPDATE goals SET created_by=null WHERE created_by=$1',[old.id]);await client.query('UPDATE results SET created_by=null WHERE created_by=$1',[old.id]);await client.query('DELETE FROM imports WHERE uploaded_by=$1',[old.id]);await client.query('DELETE FROM action_comments WHERE user_id=$1',[old.id]);await client.query('DELETE FROM messages WHERE sender_id=$1',[old.id]);await client.query('DELETE FROM conversations WHERE created_by=$1',[old.id]);await client.query('DELETE FROM actions WHERE created_by=$1',[old.id]);await client.query('DELETE FROM goal_change_requests WHERE requested_by=$1',[old.id]);await client.query('DELETE FROM notifications WHERE user_id=$1',[old.id]);await client.query('DELETE FROM conversation_members WHERE user_id=$1',[old.id]);await client.query('DELETE FROM action_targets WHERE user_id=$1 OR supervisor_id=$1',[old.id]);await client.query('DELETE FROM results WHERE user_id=$1',[old.id]);await client.query('DELETE FROM goals WHERE user_id=$1',[old.id]);await client.query('DELETE FROM users WHERE id=$1',[old.id]);await client.query('INSERT INTO audit_logs(user_id,action,entity,entity_id,old_data,ip_address) VALUES($1,$2,$3,$4,$5,$6)',[req.user.id,'HARD_DELETE','USER',old.id,publicUser(old),req.ip]);await client.query('COMMIT');res.status(204).end();}catch(error){await client.query('ROLLBACK');throw error}finally{client.release()}
}));

app.get('/api/teams',auth,route(async(req,res)=>{const ownTeam=roles[req.user.role]<=roles.SUPERVISOR;const rows=(await query(`SELECT t.*,u.name supervisor_name,(SELECT count(*) FROM users s WHERE s.team_id=t.id AND s.role='SELLER' AND s.status='ACTIVE') seller_count FROM teams t LEFT JOIN users u ON u.id=t.supervisor_id ${ownTeam?'WHERE t.id=$1':''} ORDER BY t.name`,ownTeam?[req.user.teamId]:[])).rows;res.json({items:rows});}));
app.get('/api/teams/:id/performance',auth,route(async(req,res)=>{
	if(!/^[0-9a-f-]{36}$/i.test(req.params.id))return res.status(400).json({error:'Mesa inválida.'});
	if(roles[req.user.role]<=roles.SUPERVISOR&&String(req.user.teamId)!==String(req.params.id))return res.status(403).json({error:'Mesa fora do seu escopo.'});
	const team=(await query('SELECT t.*,u.name supervisor_name,u.email supervisor_email FROM teams t LEFT JOIN users u ON u.id=t.supervisor_id WHERE t.id=$1',[req.params.id])).rows[0];
	if(!team)return res.status(404).json({error:'Mesa não encontrada.'});
	const p=await period(req.query.periodId);
	if(!p)return res.json({team,period:null,summary:{},indicators:[],sellers:[],trend:[]});
	const performanceParams=[p.id,team.id];const sellerScope=req.user.role==='SELLER'?' AND u.id=$3':'';if(req.user.role==='SELLER')performanceParams.push(req.user.id);
	const result=(await query(`SELECT g.user_id,g.indicator_id,g.target_value,u.name user_name,i.name indicator_name,i.code,i.direction,i.type,i.unit,COALESCE(sum(r.result_value),0) achieved FROM goals g JOIN users u ON u.id=g.user_id JOIN indicators i ON i.id=g.indicator_id LEFT JOIN results r ON r.user_id=g.user_id AND r.indicator_id=g.indicator_id AND r.period_id=g.period_id WHERE g.period_id=$1 AND u.team_id=$2 AND u.role='SELLER' AND u.status='ACTIVE'${sellerScope} GROUP BY g.user_id,g.indicator_id,g.target_value,u.name,i.id ORDER BY u.name,i.name`,performanceParams)).rows;
	const configuredDays=Array.isArray(p.business_days)?p.business_days.map(dateKey).filter(Boolean):[];
	const start=new Date(`${dateKey(p.start_date)}T12:00:00`);const end=new Date(`${dateKey(p.end_date)}T12:00:00`);const today=new Date();today.setHours(12,0,0,0);
	const fallbackDays=[];for(let day=new Date(start);day<=end;day.setDate(day.getDate()+1))if(day.getDay()>0&&day.getDay()<6)fallbackDays.push(day.toISOString().slice(0,10));
	const businessDays=configuredDays.length?configuredDays:fallbackDays;const todayKey=today.toISOString().slice(0,10);
	const elapsedDays=Math.max(1,businessDays.filter(day=>day<=todayKey).length);const remainingDays=businessDays.filter(day=>day>todayKey).length;
	const rows=result.map(row=>{const values=metrics(row.target_value,row.achieved,row.direction);const dailyAverage=values.achieved/elapsedDays;const projected=values.achieved+dailyAverage*remainingDays;const gap=row.direction==='LOWER_IS_BETTER'?Math.max(0,values.achieved-values.target):Math.max(0,values.target-values.achieved);const dailyNeeded=row.direction==='LOWER_IS_BETTER'?0:(remainingDays?Math.max(0,values.target-values.achieved)/remainingDays:Math.max(0,values.target-values.achieved));return {...row,...values,gap,dailyAverage,dailyNeeded,projected,projectedAchievement:metrics(values.target,projected,row.direction).achievement};});
	const group=(items,key)=>items.reduce((map,item)=>{const value=item[key];if(!map.has(value))map.set(value,[]);map.get(value).push(item);return map;},new Map());
	const average=items=>items.length?items.reduce((sum,item)=>sum+Math.min(200,Number(item.achievement||0)),0)/items.length:0;
	const projectedAverage=items=>items.length?items.reduce((sum,item)=>sum+Math.min(200,Number(item.projectedAchievement||0)),0)/items.length:0;
	const indicators=[...group(rows,'indicator_id')].map(([id,items])=>{const target=items.reduce((sum,item)=>sum+item.target,0);const achieved=items.reduce((sum,item)=>sum+item.achieved,0);const projected=items.reduce((sum,item)=>sum+item.projected,0);return {id,name:items[0].indicator_name,code:items[0].code,direction:items[0].direction,type:items[0].type,unit:items[0].unit,target,achieved,gap:items.reduce((sum,item)=>sum+item.gap,0),dailyAverage:items.reduce((sum,item)=>sum+item.dailyAverage,0),dailyNeeded:items.reduce((sum,item)=>sum+item.dailyNeeded,0),projected,achievement:average(items),projectedAchievement:projectedAverage(items),sellerCount:items.length};}).sort((a,b)=>a.achievement-b.achievement);
	const sellers=[...group(rows,'user_id')].map(([id,items])=>({id,name:items[0].user_name,achievement:average(items),projectedAchievement:projectedAverage(items),criticalIndicators:items.filter(item=>item.achievement<60).length,indicators:items})).sort((a,b)=>b.achievement-a.achievement);
	const dailyRows=(await query(`SELECT r.user_id,r.indicator_id,r.reference_date,r.result_value,g.target_value,i.direction FROM results r JOIN goals g ON g.user_id=r.user_id AND g.indicator_id=r.indicator_id AND g.period_id=r.period_id JOIN users u ON u.id=r.user_id JOIN indicators i ON i.id=r.indicator_id WHERE r.period_id=$1 AND u.team_id=$2${sellerScope} ORDER BY r.reference_date`,performanceParams)).rows;
	const dates=[...new Set(dailyRows.map(row=>dateKey(row.reference_date)))];const cumulative=new Map();const trend=dates.map(date=>{for(const row of dailyRows.filter(item=>dateKey(item.reference_date)===date)){const key=`${row.user_id}:${row.indicator_id}`;cumulative.set(key,(cumulative.get(key)||0)+Number(row.result_value));}const values=rows.map(goal=>metrics(goal.target,cumulative.get(`${goal.user_id}:${goal.indicator_id}`)||0,goal.direction).achievement);return {date,achievement:values.length?values.reduce((sum,value)=>sum+Math.min(200,value),0)/values.length:0};});
	res.json({team,period:p,summary:{sellerCount:sellers.length,indicatorCount:indicators.length,achievement:average(rows),projectedAchievement:projectedAverage(rows),criticalCount:rows.filter(row=>row.achievement<60).length,elapsedDays,remainingDays},indicators,sellers,trend});
}));
app.post('/api/teams',auth,allow('SUPER_ADMIN','MANAGER'),route(async(req,res)=>{if(!req.body.name?.trim())return res.status(400).json({error:'Nome da mesa é obrigatório.'});const supervisor=req.body.supervisorId?(await query("SELECT id FROM users WHERE id=$1 AND role='SUPERVISOR' AND status='ACTIVE'",[req.body.supervisorId])).rows[0]:null;if(req.body.supervisorId&&!supervisor)return res.status(400).json({error:'Supervisor inválido ou inativo.'});const row=(await query('INSERT INTO teams(name,supervisor_id) VALUES($1,$2) RETURNING *',[req.body.name.trim(),supervisor?.id||null])).rows[0];if(supervisor)await query('UPDATE users SET team_id=$1,updated_at=now() WHERE id=$2',[row.id,supervisor.id]);await audit(req,'CREATE','TEAM',row.id,null,row);res.status(201).json({item:row});}));
app.patch('/api/teams/:id',auth,allow('SUPER_ADMIN','MANAGER'),route(async(req,res)=>{const old=(await query('SELECT * FROM teams WHERE id=$1',[req.params.id])).rows[0];if(!old)return res.status(404).json({error:'Mesa não encontrada.'});const hasSupervisor=Object.prototype.hasOwnProperty.call(req.body,'supervisorId');const supervisorId=hasSupervisor?(req.body.supervisorId||null):old.supervisor_id;if(supervisorId&&!(await query("SELECT 1 FROM users WHERE id=$1 AND role='SUPERVISOR' AND status='ACTIVE'",[supervisorId])).rowCount)return res.status(400).json({error:'Supervisor inválido ou inativo.'});const row=(await query('UPDATE teams SET name=COALESCE($1,name),supervisor_id=$2,status=COALESCE($3,status),updated_at=now() WHERE id=$4 RETURNING *',[req.body.name?.trim()||null,supervisorId,req.body.status||null,req.params.id])).rows[0];if(String(old.supervisor_id||'')!==String(supervisorId||'')){if(old.supervisor_id)await query('UPDATE users SET team_id=null,updated_at=now() WHERE id=$1 AND team_id=$2',[old.supervisor_id,row.id]);if(supervisorId)await query('UPDATE users SET team_id=$1,updated_at=now() WHERE id=$2',[row.id,supervisorId]);}await audit(req,'UPDATE','TEAM',row.id,old,row);res.json({item:row});}));
app.delete('/api/teams/:id',auth,allow('SUPER_ADMIN','MANAGER'),route(async(req,res)=>{const client=await pool.connect();try{await client.query('BEGIN');const old=(await client.query('SELECT * FROM teams WHERE id=$1 FOR UPDATE',[req.params.id])).rows[0];if(!old){await client.query('ROLLBACK');return res.status(404).json({error:'Mesa não encontrada.'});}const actionIds=(await client.query('SELECT DISTINCT action_id FROM action_targets WHERE team_id=$1',[old.id])).rows.map(row=>row.action_id);const affectedUsers=(await client.query("UPDATE users SET team_id=null,status='INACTIVE',updated_at=now() WHERE team_id=$1 RETURNING id",[old.id])).rowCount;await client.query('DELETE FROM conversations WHERE team_id=$1',[old.id]);await client.query('DELETE FROM teams WHERE id=$1',[old.id]);if(actionIds.length)await client.query('DELETE FROM actions WHERE id=ANY($1::uuid[]) AND NOT EXISTS (SELECT 1 FROM action_targets WHERE action_targets.action_id=actions.id)',[actionIds]);await client.query('INSERT INTO audit_logs(user_id,action,entity,entity_id,old_data,new_data,ip_address) VALUES($1,$2,$3,$4,$5,$6,$7)',[req.user.id,'HARD_DELETE','TEAM',old.id,JSON.stringify(old),JSON.stringify({affectedUsers}),req.ip]);await client.query('COMMIT');res.status(204).end();}catch(error){await client.query('ROLLBACK');throw error}finally{client.release()}}));

app.get('/api/periods',auth,route(async(_req,res)=>res.json({items:(await query('SELECT * FROM periods ORDER BY start_date DESC')).rows})));
app.post('/api/periods',auth,allow('SUPER_ADMIN','MANAGER'),route(async(req,res)=>{const {name,month,year,startDate,endDate,status}=req.body;if(!name?.trim()||!/^\d{4}-\d{2}-\d{2}$/.test(startDate||'')||!/^\d{4}-\d{2}-\d{2}$/.test(endDate||'')||startDate>endDate)return res.status(400).json({error:'Nome e intervalo de datas válido são obrigatórios.'});const row=(await query('INSERT INTO periods(name,month,year,start_date,end_date,status) VALUES($1,$2,$3,$4,$5,$6) RETURNING *',[name.trim(),month,year,startDate,endDate,status||'DRAFT'])).rows[0];await audit(req,'CREATE','PERIOD',row.id,null,row);res.status(201).json({item:row});}));
app.patch('/api/periods/:id',auth,allow('SUPER_ADMIN','MANAGER'),route(async(req,res)=>{const old=(await query('SELECT * FROM periods WHERE id=$1',[req.params.id])).rows[0];if(!old)return res.status(404).json({error:'Período não encontrado.'});const row=(await query('UPDATE periods SET name=COALESCE($1,name),month=COALESCE($2,month),year=COALESCE($3,year),start_date=COALESCE($4,start_date),end_date=COALESCE($5,end_date),status=COALESCE($6,status),business_days=COALESCE($7,business_days),updated_at=now() WHERE id=$8 RETURNING *',[req.body.name?.trim()||null,req.body.month||null,req.body.year||null,req.body.startDate||null,req.body.endDate||null,req.body.status||null,req.body.businessDays?JSON.stringify(req.body.businessDays):null,req.params.id])).rows[0];await audit(req,'UPDATE','PERIOD',row.id,old,row);res.json({item:row});}));
app.delete('/api/periods/:id',auth,allow('SUPER_ADMIN','MANAGER'),route(async(req,res)=>{const old=(await query('SELECT * FROM periods WHERE id=$1',[req.params.id])).rows[0];if(!old)return res.status(404).json({error:'Período não encontrado.'});const usage=(await query('SELECT (SELECT count(*) FROM goals WHERE period_id=$1)+(SELECT count(*) FROM results WHERE period_id=$1)+(SELECT count(*) FROM imports WHERE period_id=$1)+(SELECT count(*) FROM actions WHERE period_id=$1) count',[old.id])).rows[0];if(Number(usage.count)>0)return res.status(409).json({error:'O período possui metas, resultados, importações ou ações e não pode ser excluído.'});await query('DELETE FROM periods WHERE id=$1',[old.id]);await audit(req,'DELETE','PERIOD',old.id,old,null);res.status(204).end();}));
app.get('/api/indicators',auth,route(async(_req,res)=>res.json({items:(await query('SELECT * FROM indicators ORDER BY name')).rows})));
app.post('/api/indicators',auth,allow('SUPER_ADMIN'),route(async(req,res)=>{const {name,code,type,direction,unit}=req.body;const row=(await query('INSERT INTO indicators(name,code,type,direction,unit) VALUES($1,$2,$3,$4,$5) RETURNING *',[name,normalize(code).toUpperCase(),type,direction,unit])).rows[0];await audit(req,'CREATE','INDICATOR',row.id,null,row);res.status(201).json({item:row});}));
app.patch('/api/indicators/:id',auth,allow('SUPER_ADMIN'),route(async(req,res)=>{const row=(await query('UPDATE indicators SET name=COALESCE($1,name),active=COALESCE($2,active),direction=COALESCE($3,direction),updated_at=now() WHERE id=$4 RETURNING *',[req.body.name||null,typeof req.body.active==='boolean'?req.body.active:null,req.body.direction||null,req.params.id])).rows[0];res.json({item:row});}));
app.delete('/api/indicators/:id',auth,allow('SUPER_ADMIN'),route(async(req,res)=>{const old=(await query('SELECT * FROM indicators WHERE id=$1',[req.params.id])).rows[0];if(!old)return res.status(404).json({error:'Indicador não encontrado.'});const row=(await query('UPDATE indicators SET active=false,updated_at=now() WHERE id=$1 RETURNING *',[old.id])).rows[0];await audit(req,'DELETE','INDICATOR',row.id,old,row);res.status(204).end();}));
app.get('/api/settings',auth,allow('SUPER_ADMIN'),route(async(_req,res)=>res.json({items:(await query("SELECT * FROM settings WHERE key<>'data_source_connection' ORDER BY key")).rows})));
app.patch('/api/settings/:key',auth,allow('SUPER_ADMIN'),route(async(req,res)=>{if(req.params.key==='data_source_connection')return res.status(400).json({error:'Use a configuração protegida de fonte de dados.'});const row=(await query('INSERT INTO settings(key,value,updated_at) VALUES($1,$2,now()) ON CONFLICT(key) DO UPDATE SET value=EXCLUDED.value,updated_at=now() RETURNING *',[req.params.key,JSON.stringify(req.body.value)])).rows[0];await audit(req,'UPDATE','SETTING',null,null,row);res.json({item:row});}));
app.delete('/api/settings/:key',auth,allow('SUPER_ADMIN'),route(async(req,res)=>{if(req.params.key==='data_source_connection')return res.status(400).json({error:'Use a configuração protegida de fonte de dados.'});const old=(await query('DELETE FROM settings WHERE key=$1 RETURNING *',[req.params.key])).rows[0];if(!old)return res.status(404).json({error:'Configuração não encontrada.'});await audit(req,'DELETE','SETTING',null,old,null);res.status(204).end();}));
app.get('/api/data-source',auth,allow('SUPER_ADMIN'),route(async(_req,res)=>{const row=(await query("SELECT value,updated_at FROM settings WHERE key='data_source_connection'")).rows[0];if(!row)return res.json({item:null});const {passwordEncrypted,...safe}=row.value;res.json({item:{...safe,hasPassword:Boolean(passwordEncrypted),updatedAt:row.updated_at}});}));
app.patch('/api/data-source',auth,allow('SUPER_ADMIN'),route(async(req,res)=>{const {type,address,database,username,password,enabled}=req.body;if(!['SERVER','CUBE'].includes(type)||!address?.trim()||!username?.trim())return res.status(400).json({error:'Tipo, endereço e login são obrigatórios.'});if(address.length>500||String(database||'').length>160||username.length>160)return res.status(400).json({error:'Os dados da conexão excedem o tamanho permitido.'});const current=(await query("SELECT value FROM settings WHERE key='data_source_connection'")).rows[0]?.value;if(!password&&!current?.passwordEncrypted)return res.status(400).json({error:'Informe a senha da fonte de dados.'});const value={type,address:address.trim(),database:String(database||'').trim(),username:username.trim(),passwordEncrypted:password?encryptSecret(password):current.passwordEncrypted,enabled:enabled!==false};await query("INSERT INTO settings(key,value,updated_at) VALUES('data_source_connection',$1,now()) ON CONFLICT(key) DO UPDATE SET value=EXCLUDED.value,updated_at=now()",[JSON.stringify(value)]);const safe={type:value.type,address:value.address,database:value.database,username:value.username,enabled:value.enabled,hasPassword:true};await audit(req,'UPDATE','DATA_SOURCE',null,null,safe);res.json({item:safe});}));
app.delete('/api/data-source',auth,allow('SUPER_ADMIN'),route(async(req,res)=>{const old=(await query("DELETE FROM settings WHERE key='data_source_connection' RETURNING value")).rows[0];if(!old)return res.status(404).json({error:'Fonte de dados não configurada.'});const {passwordEncrypted,...safe}=old.value;await audit(req,'DELETE','DATA_SOURCE',null,safe,null);res.status(204).end();}));
app.get('/api/module-access',auth,route(async(_req,res)=>res.json({access:await configuredModuleAccess()})));
app.patch('/api/module-access',auth,allow('SUPER_ADMIN'),route(async(req,res)=>{const access={};for(const role of ['MANAGER','SUPERVISOR','SELLER']){const valid=new Set(defaultModuleAccess[role]);const requested=Array.isArray(req.body.access?.[role])?req.body.access[role]:defaultModuleAccess[role];access[role]=['DASHBOARD',...new Set(requested.filter(value=>value!=='DASHBOARD'&&valid.has(value)))];}await query("INSERT INTO settings(key,value,updated_at) VALUES('module_access',$1,now()) ON CONFLICT(key) DO UPDATE SET value=EXCLUDED.value,updated_at=now()",[JSON.stringify(access)]);await audit(req,'UPDATE','MODULE_ACCESS',null,null,access);res.json({access});}));

app.get('/api/goals',auth,route(async(req,res)=>{const p=await period(req.query.periodId);if(!p)return res.json({period:null,items:[]});let scoped='',params=[p.id];if(req.user.role==='SUPERVISOR'){scoped=' AND u.team_id=$2';params.push(req.user.teamId);}if(req.user.role==='SELLER'){scoped=' AND u.id=$2';params.push(req.user.id);}const rows=(await query(`SELECT g.*,u.name user_name,u.team_id,i.name indicator_name,i.code,i.direction,i.type,i.unit,COALESCE(sum(r.result_value),0) achieved FROM goals g JOIN users u ON u.id=g.user_id JOIN indicators i ON i.id=g.indicator_id LEFT JOIN results r ON r.user_id=g.user_id AND r.indicator_id=g.indicator_id AND r.period_id=g.period_id WHERE g.period_id=$1 ${scoped} GROUP BY g.id,u.id,i.id ORDER BY u.name,i.name`,params)).rows;res.json({period:p,items:rows.map(row=>({...row,...metrics(row.target_value,row.achieved,row.direction)}))});}));
app.post('/api/goals',auth,allow('SUPER_ADMIN','MANAGER','SUPERVISOR'),route(async(req,res)=>{const {userId,indicatorId,periodId,targetValue,changeRequestId}=req.body;const p=await period(periodId);if(!p)return res.status(400).json({error:'Período inválido.'});const seller=(await query('SELECT id,team_id FROM users WHERE id=$1',[userId])).rows[0];if(!seller)return res.status(404).json({error:'Vendedor não encontrado.'});if(req.user.role==='SUPERVISOR'&&seller.team_id!==req.user.teamId)return res.status(403).json({error:'Vendedor fora da sua mesa.'});const old=(await query('SELECT * FROM goals WHERE user_id=$1 AND indicator_id=$2 AND period_id=$3',[userId,indicatorId,p.id])).rows[0];if(old&&req.user.role==='SUPERVISOR'&&new Date().getDate()>10){const approved=(await query("SELECT id FROM goal_change_requests WHERE id=$1 AND goal_id=$2 AND requested_by=$3 AND status='APPROVED' AND (expires_at IS NULL OR expires_at>now())",[changeRequestId||'',old.id,req.user.id])).rows[0];if(!approved)return res.status(423).json({error:'Edição bloqueada após o dia 10. Solicite autorização ao gerente.'});await query("UPDATE goal_change_requests SET status='USED' WHERE id=$1",[approved.id]);}const row=(await query('INSERT INTO goals(user_id,indicator_id,period_id,target_value,created_by) VALUES($1,$2,$3,$4,$5) ON CONFLICT(user_id,indicator_id,period_id) DO UPDATE SET target_value=EXCLUDED.target_value,updated_at=now() RETURNING *',[userId,indicatorId,p.id,targetValue,req.user.id])).rows[0];await audit(req,old?'UPDATE':'CREATE','GOAL',row.id,old,row);res.status(old?200:201).json({item:row});}));
app.delete('/api/goals/:id',auth,allow('SUPER_ADMIN','MANAGER','SUPERVISOR'),route(async(req,res)=>{const old=(await query('SELECT g.*,u.team_id FROM goals g JOIN users u ON u.id=g.user_id WHERE g.id=$1',[req.params.id])).rows[0];if(!old)return res.status(404).json({error:'Meta não encontrada.'});if(req.user.role==='SUPERVISOR'&&String(old.team_id)!==String(req.user.teamId))return res.status(403).json({error:'Meta fora da sua mesa.'});if(req.user.role==='SUPERVISOR'&&new Date().getDate()>10)return res.status(423).json({error:'Exclusão bloqueada após o dia 10.'});await query('DELETE FROM goals WHERE id=$1',[old.id]);await audit(req,'DELETE','GOAL',old.id,old,null);res.status(204).end();}));
app.post('/api/goal-change-requests',auth,allow('SUPERVISOR'),route(async(req,res)=>{const goal=(await query('SELECT g.*,u.team_id FROM goals g JOIN users u ON u.id=g.user_id WHERE g.id=$1',[req.body.goalId])).rows[0];if(!goal||goal.team_id!==req.user.teamId)return res.status(404).json({error:'Meta não encontrada.'});const row=(await query('INSERT INTO goal_change_requests(goal_id,requested_by,old_value,new_value,reason) VALUES($1,$2,$3,$4,$5) RETURNING *',[goal.id,req.user.id,goal.target_value,req.body.newValue,req.body.reason])).rows[0];await audit(req,'REQUEST_CHANGE','GOAL',goal.id,null,row);res.status(201).json({item:row});}));
app.get('/api/goal-change-requests',auth,allow('SUPER_ADMIN','MANAGER','SUPERVISOR'),route(async(req,res)=>{const own=req.user.role==='SUPERVISOR';const rows=(await query(`SELECT r.*,u.name seller_name,i.name indicator_name FROM goal_change_requests r JOIN goals g ON g.id=r.goal_id JOIN users u ON u.id=g.user_id JOIN indicators i ON i.id=g.indicator_id ${own?'WHERE r.requested_by=$1':''} ORDER BY r.requested_at DESC`,own?[req.user.id]:[])).rows;res.json({items:rows});}));
app.patch('/api/goal-change-requests/:id',auth,allow('SUPER_ADMIN','MANAGER'),route(async(req,res)=>{if(!['APPROVED','REJECTED'].includes(req.body.status))return res.status(400).json({error:'Status inválido.'});const row=(await query("UPDATE goal_change_requests SET status=$1::varchar,approved_by=$2,approved_at=now(),expires_at=CASE WHEN $1::varchar='APPROVED' THEN now()+interval '24 hours' ELSE null END WHERE id=$3 AND status='PENDING' RETURNING *",[req.body.status,req.user.id,req.params.id])).rows[0];if(!row)return res.status(404).json({error:'Solicitação pendente não encontrada.'});await audit(req,req.body.status,'GOAL_CHANGE_REQUEST',row.id,null,row);res.json({item:row});}));
app.delete('/api/goal-change-requests/:id',auth,allow('SUPER_ADMIN','MANAGER','SUPERVISOR'),route(async(req,res)=>{const params=[req.params.id];const own=req.user.role==='SUPERVISOR';if(own)params.push(req.user.id);const row=(await query(`DELETE FROM goal_change_requests WHERE id=$1 AND status='PENDING'${own?' AND requested_by=$2':''} RETURNING *`,params)).rows[0];if(!row)return res.status(404).json({error:'Solicitação pendente não encontrada no seu escopo.'});await audit(req,'DELETE','GOAL_CHANGE_REQUEST',row.id,row,null);res.status(204).end();}));

app.get('/api/results',auth,route(async(req,res)=>{let where='';const params=[];if(req.query.periodId){params.push(req.query.periodId);where+=` AND r.period_id=$${params.length}`;}if(req.user.role==='SUPERVISOR'){params.push(req.user.teamId);where+=` AND u.team_id=$${params.length}`;}else if(req.user.role==='SELLER'){params.push(req.user.id);where+=` AND u.id=$${params.length}`;}const items=(await query(`SELECT r.*,u.name user_name,u.team_id,i.name indicator_name,i.unit,p.name period_name,c.name created_by_name FROM results r JOIN users u ON u.id=r.user_id JOIN indicators i ON i.id=r.indicator_id JOIN periods p ON p.id=r.period_id LEFT JOIN users c ON c.id=r.created_by WHERE 1=1${where} ORDER BY r.reference_date DESC,r.created_at DESC`,params)).rows;res.json({items});}));
app.post('/api/results',auth,allow('SUPER_ADMIN','MANAGER','SUPERVISOR'),route(async(req,res)=>{const {userId,indicatorId,periodId,resultValue,referenceDate}=req.body;const p=await period(periodId);if(!p)return res.status(400).json({error:'Período inválido.'});const seller=(await query('SELECT * FROM users WHERE id=$1',[userId])).rows[0];if(!seller)return res.status(404).json({error:'Vendedor não encontrado.'});if(req.user.role==='SUPERVISOR'&&seller.team_id!==req.user.teamId)return res.status(403).json({error:'Vendedor fora da sua mesa.'});const row=(await query("INSERT INTO results(user_id,indicator_id,period_id,result_value,reference_date,source,created_by) VALUES($1,$2,$3,$4,$5,'MANUAL',$6) ON CONFLICT(user_id,indicator_id,period_id,reference_date) DO UPDATE SET result_value=EXCLUDED.result_value,created_by=EXCLUDED.created_by RETURNING *",[userId,indicatorId,p.id,resultValue,referenceDate,req.user.id])).rows[0];await audit(req,'UPSERT','RESULT',row.id,null,row);res.status(201).json({item:row});}));
app.patch('/api/results/:id',auth,allow('SUPER_ADMIN','MANAGER','SUPERVISOR'),route(async(req,res)=>{const old=(await query('SELECT r.*,u.team_id FROM results r JOIN users u ON u.id=r.user_id WHERE r.id=$1',[req.params.id])).rows[0];if(!old)return res.status(404).json({error:'Resultado não encontrado.'});if(req.user.role==='SUPERVISOR'&&String(old.team_id)!==String(req.user.teamId))return res.status(403).json({error:'Resultado fora da sua mesa.'});const value=numeric(req.body.resultValue);if(value===null)return res.status(400).json({error:'Resultado inválido.'});const row=(await query('UPDATE results SET result_value=$1,reference_date=COALESCE($2,reference_date),created_by=$3 WHERE id=$4 RETURNING *',[value,req.body.referenceDate||null,req.user.id,old.id])).rows[0];await audit(req,'UPDATE','RESULT',row.id,old,row);res.json({item:row});}));
app.delete('/api/results/:id',auth,allow('SUPER_ADMIN','MANAGER','SUPERVISOR'),route(async(req,res)=>{const old=(await query('SELECT r.*,u.team_id FROM results r JOIN users u ON u.id=r.user_id WHERE r.id=$1',[req.params.id])).rows[0];if(!old)return res.status(404).json({error:'Resultado não encontrado.'});if(req.user.role==='SUPERVISOR'&&String(old.team_id)!==String(req.user.teamId))return res.status(403).json({error:'Resultado fora da sua mesa.'});await query('DELETE FROM results WHERE id=$1',[old.id]);await audit(req,'DELETE','RESULT',old.id,old,null);res.status(204).end();}));

app.get('/api/dashboard',auth,route(async(req,res)=>{
	const p=await period(req.query.periodId);
	if(!p)return res.json({period:null,summary:{},teams:[],ranking:[],supervisorRanking:[],indicators:[],trend:[],actions:{},activity:[],alerts:[]});
	let scoped='';const params=[p.id];
	if(req.user.role==='SUPERVISOR'){scoped=' AND u.team_id=$2';params.push(req.user.teamId);}
	if(req.user.role==='SELLER'){scoped=' AND u.id=$2';params.push(req.user.id);}
	const goalRows=(await query(`SELECT g.id,g.user_id,g.indicator_id,g.target_value,u.name user_name,u.team_id,t.name team_name,t.supervisor_id,s.name supervisor_name,i.name indicator_name,i.code,i.direction,i.unit,COALESCE(sum(r.result_value),0) achieved FROM goals g JOIN users u ON u.id=g.user_id LEFT JOIN teams t ON t.id=u.team_id LEFT JOIN users s ON s.id=t.supervisor_id JOIN indicators i ON i.id=g.indicator_id LEFT JOIN results r ON r.user_id=g.user_id AND r.indicator_id=g.indicator_id AND r.period_id=g.period_id WHERE g.period_id=$1 AND u.status='ACTIVE' AND u.role='SELLER' ${scoped} GROUP BY g.id,u.id,t.id,s.name,i.id ORDER BY u.name,i.name`,params)).rows.map(row=>({...row,...metrics(row.target_value,row.achieved,row.direction)}));
	const periodEnd=new Date(`${dateKey(p.end_date)}T23:59:59`);const periodStart=new Date(`${dateKey(p.start_date)}T00:00:00`);
	const daysRemaining=Math.max(0,Math.ceil((periodEnd-new Date())/86400000));
	const elapsedDays=Math.max(1,Math.ceil((Math.min(new Date(),periodEnd)-periodStart)/86400000));
	const average=rows=>rows.length?rows.reduce((sum,row)=>sum+Math.min(150,Number(row.achievement||0)),0)/rows.length:0;
	const summary={goalCount:goalRows.length,sellerCount:new Set(goalRows.map(row=>row.user_id)).size,target:goalRows.reduce((sum,row)=>sum+Number(row.target||0),0),achieved:goalRows.reduce((sum,row)=>sum+Number(row.achieved||0),0),achievement:average(goalRows),daysRemaining};
	summary.remaining=Math.max(0,summary.target-summary.achieved);summary.dailyTarget=daysRemaining?summary.remaining/daysRemaining:summary.remaining;summary.projectedAchievement=Math.min(200,summary.achievement/elapsedDays*Math.max(elapsedDays+daysRemaining,1));
	const group=(rows,key)=>rows.reduce((map,row)=>{const value=row[key]||'Sem vínculo';if(!map.has(value))map.set(value,[]);map.get(value).push(row);return map;},new Map());
	const teams=[...group(goalRows,'team_name')].map(([name,rows])=>({name,teamId:rows[0].team_id,sellers:new Set(rows.map(row=>row.user_id)).size,target:rows.reduce((sum,row)=>sum+Number(row.target),0),achieved:rows.reduce((sum,row)=>sum+Number(row.achieved),0),achievement:average(rows),riskCount:new Set(rows.filter(row=>row.achievement<60).map(row=>row.user_id)).size})).sort((a,b)=>a.name.localeCompare(b.name));
	const ranking=[...group(goalRows,'user_id')].map(([id,rows])=>({id,name:rows[0].user_name,team_name:rows[0].team_name,achievement:average(rows),criticalIndicators:rows.filter(row=>row.achievement<60).length})).sort((a,b)=>b.achievement-a.achievement).slice(0,10);
	const supervisorRanking=[...group(goalRows.filter(row=>row.supervisor_id),'supervisor_id')].map(([id,rows])=>({id,name:rows[0].supervisor_name,team_name:rows[0].team_name,sellerCount:new Set(rows.map(row=>row.user_id)).size,achievement:average(rows),criticalSellers:new Set(rows.filter(row=>row.achievement<60).map(row=>row.user_id)).size})).sort((a,b)=>b.achievement-a.achievement).slice(0,10);
	const indicators=[...group(goalRows,'indicator_id')].map(([id,rows])=>({id,name:rows[0].indicator_name,code:rows[0].code,unit:rows[0].unit,direction:rows[0].direction,target:rows.reduce((sum,row)=>sum+Number(row.target),0),achieved:rows.reduce((sum,row)=>sum+Number(row.achieved),0),achievement:average(rows),riskCount:new Set(rows.filter(row=>row.achievement<60).map(row=>row.user_id)).size,sellers:new Set(rows.map(row=>row.user_id)).size})).sort((a,b)=>a.achievement-b.achievement);
	const resultRows=(await query(`SELECT r.user_id,r.indicator_id,r.reference_date,r.result_value,g.target_value,i.direction FROM results r JOIN goals g ON g.user_id=r.user_id AND g.indicator_id=r.indicator_id AND g.period_id=r.period_id JOIN users u ON u.id=r.user_id JOIN indicators i ON i.id=r.indicator_id WHERE r.period_id=$1 ${scoped} ORDER BY r.reference_date`,params)).rows;
	const dates=[...new Set(resultRows.map(row=>dateKey(row.reference_date)))];const cumulative=new Map();
	const trend=dates.map(date=>{for(const row of resultRows.filter(item=>dateKey(item.reference_date)===date)){const key=`${row.user_id}:${row.indicator_id}`;cumulative.set(key,(cumulative.get(key)||0)+Number(row.result_value));}const values=goalRows.map(goal=>metrics(goal.target_value,cumulative.get(`${goal.user_id}:${goal.indicator_id}`)||0,goal.direction).achievement);return {date,achievement:values.length?values.reduce((sum,value)=>sum+Math.min(150,value),0)/values.length:0};});
	let actionWhere='';let actionParams=[];if(req.user.role==='SUPERVISOR'){actionWhere='WHERE EXISTS (SELECT 1 FROM action_targets at WHERE at.action_id=a.id AND at.team_id=$1)';actionParams=[req.user.teamId];}else if(req.user.role==='SELLER'){actionWhere='WHERE EXISTS (SELECT 1 FROM action_targets at WHERE at.action_id=a.id AND at.user_id=$1)';actionParams=[req.user.id];}
	const actionRows=(await query(`SELECT a.status,a.priority FROM actions a ${actionWhere}`,actionParams)).rows;const actions={active:actionRows.filter(row=>['CREATED','DISTRIBUTED','IN_PROGRESS','AT_RISK'].includes(row.status)).length,atRisk:actionRows.filter(row=>row.status==='AT_RISK').length,completed:actionRows.filter(row=>row.status==='COMPLETED').length};
	const activityWhere=roles[req.user.role]>=roles.MANAGER?'':'WHERE a.user_id=$1';const activityParams=roles[req.user.role]>=roles.MANAGER?[]:[req.user.id];
	const activity=(await query(`SELECT a.action,a.entity,a.created_at,u.name user_name FROM audit_logs a LEFT JOIN users u ON u.id=a.user_id ${activityWhere} ORDER BY a.created_at DESC LIMIT 6`,activityParams)).rows;
	const alerts=[];for(const indicator of indicators.filter(item=>item.achievement<80).slice(0,3))alerts.push({level:indicator.achievement<60?'CRITICAL':'WARNING',message:`${indicator.name} está em ${Math.round(indicator.achievement)}% com ${indicator.riskCount} vendedor(es) em risco.`});for(const team of teams.filter(item=>item.achievement<60))alerts.push({level:'CRITICAL',message:`${team.name} precisa acelerar: ${team.riskCount} vendedor(es) em risco.`});
	res.json({period:p,summary,teams,ranking,supervisorRanking,indicators,trend,actions,activity,alerts,focus:indicators[0]||null});
}));

app.get('/api/actions',auth,route(async(req,res)=>{let where='';let params=[];let targetScope='at.user_id IS NOT NULL';let scopeTarget='a.target_value';if(req.user.role==='SUPERVISOR'){where='WHERE EXISTS (SELECT 1 FROM action_targets own WHERE own.action_id=a.id AND own.team_id=$1)';params=[req.user.teamId];targetScope='at.team_id=$1 AND at.user_id IS NOT NULL';scopeTarget='COALESCE((SELECT max(own.target_value) FROM action_targets own WHERE own.action_id=a.id AND own.team_id=$1 AND own.user_id IS NULL),a.target_value)';}else if(req.user.role==='SELLER'){where='WHERE EXISTS (SELECT 1 FROM action_targets own WHERE own.action_id=a.id AND own.user_id=$1)';params=[req.user.id];targetScope='at.user_id=$1';scopeTarget='COALESCE((SELECT max(own.assigned_value) FROM action_targets own WHERE own.action_id=a.id AND own.user_id=$1),0)';}const items=(await query(`SELECT a.*,i.name indicator_name,p.name period_name,u.name created_by_name,${scopeTarget} scope_target_value,COALESCE((SELECT sum(at.assigned_value) FROM action_targets at WHERE at.action_id=a.id AND ${targetScope}),0) assigned_value,COALESCE((SELECT sum(at.progress_value) FROM action_targets at WHERE at.action_id=a.id AND ${targetScope}),0) progress_value,COALESCE((SELECT string_agg(DISTINCT t.name,', ' ORDER BY t.name) FROM action_targets at JOIN teams t ON t.id=at.team_id WHERE at.action_id=a.id ${req.user.role==='SUPERVISOR'?'AND at.team_id=$1':''}),'') teams FROM actions a LEFT JOIN indicators i ON i.id=a.indicator_id LEFT JOIN periods p ON p.id=a.period_id JOIN users u ON u.id=a.created_by ${where} ORDER BY CASE a.priority WHEN 'CRITICAL' THEN 1 WHEN 'HIGH' THEN 2 WHEN 'NORMAL' THEN 3 ELSE 4 END,a.end_date`,params)).rows;const summary={active:items.filter(item=>['CREATED','DISTRIBUTED','IN_PROGRESS','AT_RISK'].includes(item.status)).length,inProgress:items.filter(item=>item.status==='IN_PROGRESS').length,atRisk:items.filter(item=>item.status==='AT_RISK').length,completed:items.filter(item=>item.status==='COMPLETED').length,overdue:items.filter(item=>item.status==='OVERDUE'||(new Date(item.end_date)<new Date()&&!['COMPLETED','CANCELLED'].includes(item.status))).length};res.json({items,summary});}));
app.post('/api/actions',auth,allow('SUPER_ADMIN','MANAGER'),route(async(req,res)=>{const {title,description,type,priority,indicatorId,periodId,startDate,endDate,targetValue,expectedResult,successIndicator,teamIds=[]}=req.body;if(!title||!type||!startDate||!endDate||numeric(targetValue)===null)return res.status(400).json({error:'Título, tipo, período e meta da ação são obrigatórios.'});if(!['RECOVERY','ACCELERATION','CORRECTION','OPPORTUNITY','FOLLOW_UP','TRAINING','CAMPAIGN','CHALLENGE'].includes(type))return res.status(400).json({error:'Tipo de ação inválido.'});if(!teamIds.length||teamIds.some(id=>!/^[0-9a-f-]{36}$/i.test(id)))return res.status(400).json({error:'Selecione ao menos uma mesa válida.'});const validTeams=(await query("SELECT id,supervisor_id FROM teams WHERE id=ANY($1::uuid[]) AND status='ACTIVE'",[teamIds])).rows;if(validTeams.length!==new Set(teamIds).size)return res.status(400).json({error:'A ação contém mesa inexistente ou inativa.'});const row=(await query("INSERT INTO actions(title,description,type,priority,status,indicator_id,period_id,created_by,start_date,end_date,target_value,expected_result,success_indicator) VALUES($1,$2,$3,$4,'CREATED',$5,$6,$7,$8,$9,$10,$11,$12) RETURNING *",[title,description||null,type,priority||'NORMAL',indicatorId||null,periodId||null,req.user.id,startDate,endDate,targetValue,expectedResult||null,successIndicator||null])).rows[0];const perTeam=Number(targetValue)/validTeams.length;for(const team of validTeams)await query('INSERT INTO action_targets(action_id,team_id,supervisor_id,target_value) VALUES($1,$2,$3,$4)',[row.id,team.id,team.supervisor_id,perTeam]);await query("INSERT INTO action_history(action_id,user_id,action,new_data) VALUES($1,$2,'CREATED',$3)",[row.id,req.user.id,JSON.stringify(row)]);await audit(req,'CREATE','ACTION',row.id,null,row);res.status(201).json({item:row});}));
app.get('/api/actions/:id',auth,route(async(req,res)=>{const item=await actionAccess(req,req.params.id);if(!item)return res.status(404).json({error:'Ação não encontrada.'});let targetFilter='';let targetParams=[item.id];if(req.user.role==='SUPERVISOR'){targetFilter=' AND at.team_id=$2';targetParams.push(req.user.teamId);}else if(req.user.role==='SELLER'){targetFilter=' AND at.user_id=$2';targetParams.push(req.user.id);}const targets=(await query(`SELECT at.*,t.name team_name,u.name user_name,s.name supervisor_name FROM action_targets at LEFT JOIN teams t ON t.id=at.team_id LEFT JOIN users u ON u.id=at.user_id LEFT JOIN users s ON s.id=at.supervisor_id WHERE at.action_id=$1${targetFilter} ORDER BY (at.user_id IS NOT NULL),u.name`,targetParams)).rows;const comments=(await query('SELECT c.*,u.name user_name,u.role FROM action_comments c JOIN users u ON u.id=c.user_id WHERE c.action_id=$1 ORDER BY c.created_at',[item.id])).rows;const history=roles[req.user.role]>=roles.SUPERVISOR?(await query('SELECT h.*,u.name user_name FROM action_history h LEFT JOIN users u ON u.id=h.user_id WHERE h.action_id=$1 ORDER BY h.created_at DESC',[item.id])).rows:[];res.json({item,targets,comments,history});}));
app.patch('/api/actions/:id',auth,allow('SUPER_ADMIN','MANAGER'),route(async(req,res)=>{const old=(await query('SELECT * FROM actions WHERE id=$1',[req.params.id])).rows[0];if(!old)return res.status(404).json({error:'Ação não encontrada.'});const allowedStatus=['DRAFT','CREATED','DISTRIBUTED','IN_PROGRESS','AT_RISK','COMPLETED','OVERDUE','CANCELLED'];if(req.body.status&&!allowedStatus.includes(req.body.status))return res.status(400).json({error:'Status inválido.'});const row=(await query("UPDATE actions SET title=COALESCE($1,title),description=COALESCE($2,description),priority=COALESCE($3,priority),status=COALESCE($4,status),end_date=COALESCE($5,end_date),completed_at=CASE WHEN $4='COMPLETED' THEN now() ELSE completed_at END,updated_at=now() WHERE id=$6 RETURNING *",[req.body.title||null,req.body.description||null,req.body.priority||null,req.body.status||null,req.body.endDate||null,req.params.id])).rows[0];await query("INSERT INTO action_history(action_id,user_id,action,old_data,new_data) VALUES($1,$2,'UPDATED',$3,$4)",[row.id,req.user.id,JSON.stringify(old),JSON.stringify(row)]);await audit(req,'UPDATE','ACTION',row.id,old,row);res.json({item:row});}));
app.delete('/api/actions/:id',auth,allow('SUPER_ADMIN','MANAGER'),route(async(req,res)=>{const old=(await query('SELECT * FROM actions WHERE id=$1',[req.params.id])).rows[0];if(!old)return res.status(404).json({error:'Ação não encontrada.'});await query('DELETE FROM actions WHERE id=$1',[old.id]);await audit(req,'DELETE','ACTION',old.id,old,null);res.status(204).end();}));
app.get('/api/actions/:id/distribution-suggestion',auth,allow('SUPER_ADMIN','MANAGER','SUPERVISOR'),route(async(req,res)=>{const item=await actionAccess(req,req.params.id);if(!item)return res.status(404).json({error:'Ação não encontrada.'});const teamId=req.user.role==='SUPERVISOR'?req.user.teamId:req.query.teamId;if(!teamId)return res.status(400).json({error:'Mesa obrigatória.'});const teamTarget=(await query('SELECT * FROM action_targets WHERE action_id=$1 AND team_id=$2 AND user_id IS NULL',[item.id,teamId])).rows[0];if(!teamTarget)return res.status(404).json({error:'Ação não direcionada para esta mesa.'});const sellers=(await query(`SELECT u.id,u.name,COALESCE(g.target_value,0) target,COALESCE(sum(r.result_value),0) achieved,COALESCE(sum(r.result_value),0)/GREATEST(1,EXTRACT(day FROM CURRENT_DATE)) daily_capacity FROM users u LEFT JOIN goals g ON g.user_id=u.id AND g.indicator_id=$2 AND g.period_id=$3 LEFT JOIN results r ON r.user_id=u.id AND r.indicator_id=$2 AND r.period_id=$3 WHERE u.team_id=$1 AND u.role='SELLER' AND u.status='ACTIVE' GROUP BY u.id,g.target_value ORDER BY u.name`,[teamId,item.indicator_id,item.period_id])).rows;res.json({teamTarget,items:weightedAllocation(teamTarget.target_value,sellers)});}));
app.post('/api/actions/:id/distribute',auth,allow('SUPER_ADMIN','MANAGER','SUPERVISOR'),route(async(req,res)=>{const item=await actionAccess(req,req.params.id);if(!item)return res.status(404).json({error:'Ação não encontrada.'});const teamId=req.user.role==='SUPERVISOR'?req.user.teamId:req.body.teamId;const teamTarget=(await query('SELECT * FROM action_targets WHERE action_id=$1 AND team_id=$2 AND user_id IS NULL',[item.id,teamId])).rows[0];if(!teamTarget)return res.status(404).json({error:'Ação não direcionada para esta mesa.'});const allocations=Array.isArray(req.body.allocations)?req.body.allocations:[];const total=allocations.reduce((sum,allocation)=>sum+Number(allocation.assignedValue||0),0);if(!allocations.length||Math.abs(total-Number(teamTarget.target_value))>.01)return res.status(400).json({error:`A distribuição deve totalizar ${Number(teamTarget.target_value).toLocaleString('pt-BR')}.`});for(const allocation of allocations){const seller=(await query("SELECT id FROM users WHERE id=$1 AND team_id=$2 AND role='SELLER'",[allocation.userId,teamId])).rows[0];if(!seller)return res.status(403).json({error:'A distribuição contém vendedor fora da mesa.'});await query("INSERT INTO action_targets(action_id,team_id,supervisor_id,user_id,target_value,assigned_value,status) VALUES($1,$2,$3,$4,$5,$5,'ASSIGNED') ON CONFLICT(action_id,user_id) WHERE user_id IS NOT NULL DO UPDATE SET assigned_value=EXCLUDED.assigned_value,target_value=EXCLUDED.target_value,status='ASSIGNED',updated_at=now()",[item.id,teamId,teamTarget.supervisor_id,allocation.userId,allocation.assignedValue]);}await query("UPDATE action_targets SET assigned_value=$1,status='ASSIGNED',updated_at=now() WHERE id=$2",[total,teamTarget.id]);await query("UPDATE actions SET status='DISTRIBUTED',updated_at=now() WHERE id=$1 AND status IN ('CREATED','DRAFT')",[item.id]);await query("INSERT INTO action_history(action_id,user_id,action,new_data) VALUES($1,$2,'DISTRIBUTED',$3)",[item.id,req.user.id,JSON.stringify({teamId,allocations})]);await audit(req,'DISTRIBUTE','ACTION',item.id,null,{teamId,allocations});res.json({distributed:total});}));
app.patch('/api/actions/:id/progress',auth,route(async(req,res)=>{const item=await actionAccess(req,req.params.id);if(!item)return res.status(404).json({error:'Ação não encontrada.'});const userId=req.user.role==='SELLER'?req.user.id:req.body.userId;const target=(await query('SELECT at.* FROM action_targets at JOIN users u ON u.id=at.user_id WHERE at.action_id=$1 AND at.user_id=$2',[item.id,userId])).rows[0];if(!target)return res.status(404).json({error:'Atribuição individual não encontrada.'});if(req.user.role==='SUPERVISOR'&&String(target.team_id)!==String(req.user.teamId))return res.status(403).json({error:'Vendedor fora da sua mesa.'});const progress=numeric(req.body.progressValue);if(progress===null)return res.status(400).json({error:'Progresso inválido.'});const status=progress>=Number(target.assigned_value)?'COMPLETED':progress>0?'IN_PROGRESS':'ASSIGNED';const row=(await query('UPDATE action_targets SET progress_value=$1,status=$2,updated_at=now() WHERE id=$3 RETURNING *',[progress,status,target.id])).rows[0];await query("UPDATE actions SET status=CASE WHEN (SELECT bool_and(progress_value>=assigned_value) FROM action_targets WHERE action_id=$1 AND user_id IS NOT NULL) THEN 'COMPLETED' ELSE 'IN_PROGRESS' END,completed_at=CASE WHEN (SELECT bool_and(progress_value>=assigned_value) FROM action_targets WHERE action_id=$1 AND user_id IS NOT NULL) THEN now() ELSE null END,updated_at=now() WHERE id=$1",[item.id]);await query("INSERT INTO action_history(action_id,user_id,action,old_data,new_data) VALUES($1,$2,'PROGRESS_UPDATED',$3,$4)",[item.id,req.user.id,JSON.stringify(target),JSON.stringify(row)]);res.json({item:row});}));
app.post('/api/actions/:id/comments',auth,route(async(req,res)=>{const item=await actionAccess(req,req.params.id);if(!item)return res.status(404).json({error:'Ação não encontrada.'});if(!req.body.comment?.trim())return res.status(400).json({error:'Comentário vazio.'});const row=(await query('INSERT INTO action_comments(action_id,user_id,comment) VALUES($1,$2,$3) RETURNING *',[item.id,req.user.id,req.body.comment.trim()])).rows[0];await query("INSERT INTO action_history(action_id,user_id,action,new_data) VALUES($1,$2,'COMMENTED',$3)",[item.id,req.user.id,JSON.stringify({comment:row.comment})]);res.status(201).json({item:row});}));

app.post('/api/imports/preview',auth,allow('SUPER_ADMIN','MANAGER'),upload.single('file'),route(async(req,res)=>{if(!req.file)return res.status(400).json({error:'Envie uma planilha.'});const book=XLSX.read(req.file.buffer,{type:'buffer',cellDates:true});const rows=XLSX.utils.sheet_to_json(book.Sheets[book.SheetNames[0]],{defval:null,raw:false});if(!rows.length)return res.status(400).json({error:'A planilha não possui linhas.'});const headers=Object.keys(rows[0]);const mapping=Object.fromEntries(headers.map(header=>[header,aliases[normalize(header)]||null]));const sellerHeader=headers.find(header=>mapping[header]==='seller');const errors=rows.flatMap((row,index)=>row[sellerHeader]?[]:[{row:index+2,field:'Vendedor',message:'Vendedor obrigatório.'}]);const previewId=crypto.randomUUID();pendingImports.set(previewId,{name:req.file.originalname,rows,mapping,created:Date.now()});res.json({previewId,fileName:req.file.originalname,totalRows:rows.length,mapping,unknownColumns:headers.filter(h=>!mapping[h]),errors:errors.slice(0,50),sample:rows.slice(0,10)});}));
app.post('/api/imports/:previewId/confirm',auth,allow('SUPER_ADMIN','MANAGER'),route(async(req,res)=>{const pending=pendingImports.get(req.params.previewId);if(!pending)return res.status(404).json({error:'Prévia expirada. Envie o arquivo novamente.'});const p=await period(req.body.periodId);if(!p)return res.status(400).json({error:'Selecione um período.'});const mapping={...pending.mapping,...(req.body.mapping||{})};const indicators=Object.fromEntries((await query('SELECT * FROM indicators WHERE active=true')).rows.map(item=>[item.code,item]));let success=0;const errors=[];for(const [index,data] of pending.rows.entries()){try{const sellerName=data[Object.keys(mapping).find(key=>mapping[key]==='seller')];if(!sellerName)throw new Error('Vendedor ausente');const seller=(await query("SELECT id FROM users WHERE lower(name)=lower($1) AND role='SELLER'",[sellerName])).rows[0];if(!seller)throw new Error(`Vendedor inexistente: ${sellerName}`);for(const [header,code] of Object.entries(mapping)){if(!indicators[code])continue;const result=numeric(data[header]);if(result===null)continue;await query("INSERT INTO results(user_id,indicator_id,period_id,result_value,reference_date,source,created_by) VALUES($1,$2,$3,$4,$5,'IMPORT',$6) ON CONFLICT(user_id,indicator_id,period_id,reference_date) DO UPDATE SET result_value=EXCLUDED.result_value,source='IMPORT',created_by=EXCLUDED.created_by",[seller.id,indicators[code].id,p.id,result,req.body.referenceDate||new Date().toISOString().slice(0,10),req.user.id]);}success++;}catch(error){errors.push({row:index+2,message:error.message});}}const row=(await query('INSERT INTO imports(file_name,uploaded_by,period_id,status,total_rows,success_rows,error_rows,errors,mapping) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9) RETURNING *',[pending.name,req.user.id,p.id,errors.length?'PROCESSED_WITH_ERRORS':'PROCESSED',pending.rows.length,success,errors.length,JSON.stringify(errors),JSON.stringify(mapping)])).rows[0];await audit(req,'IMPORT','IMPORT',row.id,null,row);pendingImports.delete(req.params.previewId);res.json({item:row,errors});}));
app.get('/api/imports',auth,allow('SUPER_ADMIN','MANAGER'),route(async(_req,res)=>res.json({items:(await query('SELECT i.*,u.name uploaded_by_name,p.name period_name FROM imports i JOIN users u ON u.id=i.uploaded_by JOIN periods p ON p.id=i.period_id ORDER BY i.created_at DESC')).rows})));

app.get('/api/conversations',auth,route(async(req,res)=>{const items=(await query("SELECT c.*,COALESCE((SELECT m.message FROM messages m WHERE m.conversation_id=c.id ORDER BY m.created_at DESC LIMIT 1),'') last_message,COALESCE((SELECT max(m.created_at) FROM messages m WHERE m.conversation_id=c.id),c.created_at) last_activity FROM conversations c JOIN conversation_members cm ON cm.conversation_id=c.id WHERE cm.user_id=$1 ORDER BY last_activity DESC",[req.user.id])).rows;res.json({items});}));
app.post('/api/conversations',auth,route(async(req,res)=>{const {type,name,memberIds=[],teamId}=req.body;if(!['DIRECT','GROUP','ANNOUNCEMENT'].includes(type))return res.status(400).json({error:'Tipo de conversa inválido.'});if(type==='ANNOUNCEMENT'&&!['SUPER_ADMIN','MANAGER','SUPERVISOR'].includes(req.user.role))return res.status(403).json({error:'Sem permissão para comunicados.'});const members=[...new Set([req.user.id,...memberIds])];if(members.some(id=>!/^[0-9a-f-]{36}$/i.test(id))||(await query('SELECT count(*) count FROM users WHERE id=ANY($1::uuid[]) AND status=\'ACTIVE\'',[members])).rows[0].count!=members.length)return res.status(400).json({error:'A conversa contém participante inválido ou inativo.'});const row=(await query('INSERT INTO conversations(type,name,team_id,created_by) VALUES($1,$2,$3,$4) RETURNING *',[type,name||null,teamId||null,req.user.id])).rows[0];for(const member of members)await query('INSERT INTO conversation_members(conversation_id,user_id) VALUES($1,$2)',[row.id,member]);await audit(req,'CREATE','CONVERSATION',row.id,null,row);res.status(201).json({item:row});}));
app.patch('/api/conversations/:id',auth,route(async(req,res)=>{const old=(await query('SELECT * FROM conversations WHERE id=$1',[req.params.id])).rows[0];if(!old)return res.status(404).json({error:'Conversa não encontrada.'});if(String(old.created_by)!==String(req.user.id)&&roles[req.user.role]<roles.MANAGER)return res.status(403).json({error:'Somente o criador ou a gestão pode alterar esta conversa.'});const memberIds=Array.isArray(req.body.memberIds)?req.body.memberIds:null;const row=(await query('UPDATE conversations SET name=COALESCE($1,name),team_id=COALESCE($2,team_id) WHERE id=$3 RETURNING *',[req.body.name?.trim()||null,req.body.teamId||null,old.id])).rows[0];if(memberIds){await query('DELETE FROM conversation_members WHERE conversation_id=$1',[old.id]);for(const member of [...new Set([old.created_by,...memberIds])])await query('INSERT INTO conversation_members(conversation_id,user_id) VALUES($1,$2)',[old.id,member]);}await audit(req,'UPDATE','CONVERSATION',row.id,old,row);res.json({item:row});}));
app.delete('/api/conversations/:id',auth,route(async(req,res)=>{const old=(await query('SELECT * FROM conversations WHERE id=$1',[req.params.id])).rows[0];if(!old)return res.status(404).json({error:'Conversa não encontrada.'});if(String(old.created_by)!==String(req.user.id)&&roles[req.user.role]<roles.MANAGER)return res.status(403).json({error:'Somente o criador ou a gestão pode excluir esta conversa.'});await query('DELETE FROM conversations WHERE id=$1',[old.id]);await audit(req,'DELETE','CONVERSATION',old.id,old,null);res.status(204).end();}));
app.get('/api/conversations/:id/messages',auth,route(async(req,res)=>{const member=(await query('SELECT 1 FROM conversation_members WHERE conversation_id=$1 AND user_id=$2',[req.params.id,req.user.id])).rowCount;if(!member)return res.status(403).json({error:'Sem acesso a esta conversa.'});const items=(await query('SELECT m.*,u.name sender_name FROM messages m JOIN users u ON u.id=m.sender_id WHERE m.conversation_id=$1 ORDER BY m.created_at',[req.params.id])).rows;await query('UPDATE conversation_members SET last_read_at=now() WHERE conversation_id=$1 AND user_id=$2',[req.params.id,req.user.id]);res.json({items});}));
app.post('/api/conversations/:id/messages',auth,route(async(req,res)=>{if(!req.body.message?.trim())return res.status(400).json({error:'Mensagem vazia.'});const member=(await query('SELECT 1 FROM conversation_members WHERE conversation_id=$1 AND user_id=$2',[req.params.id,req.user.id])).rowCount;if(!member)return res.status(403).json({error:'Sem acesso a esta conversa.'});const row=(await query('INSERT INTO messages(sender_id,conversation_id,message) VALUES($1,$2,$3) RETURNING *',[req.user.id,req.params.id,req.body.message.trim()])).rows[0];res.status(201).json({item:row});}));
app.get('/api/notifications',auth,route(async(req,res)=>res.json({items:(await query('SELECT * FROM notifications WHERE user_id=$1 ORDER BY created_at DESC LIMIT 30',[req.user.id])).rows})));
app.patch('/api/notifications/:id/read',auth,route(async(req,res)=>{await query('UPDATE notifications SET read_at=now() WHERE id=$1 AND user_id=$2',[req.params.id,req.user.id]);res.status(204).end();}));
async function reportRows(req) { const p=await period(req.query.periodId);let scoped='',params=[p.id];if(req.user.role==='SUPERVISOR'){scoped=' AND u.team_id=$2';params.push(req.user.teamId);}if(req.user.role==='SELLER'){scoped=' AND u.id=$2';params.push(req.user.id);}const rows=(await query(`SELECT u.name vendedor,t.name mesa,i.name indicador,g.target_value meta,COALESCE(sum(r.result_value),0) realizado FROM goals g JOIN users u ON u.id=g.user_id LEFT JOIN teams t ON t.id=u.team_id JOIN indicators i ON i.id=g.indicator_id LEFT JOIN results r ON r.user_id=u.id AND r.indicator_id=i.id AND r.period_id=g.period_id WHERE g.period_id=$1 ${scoped} GROUP BY u.name,t.name,i.name,g.target_value ORDER BY u.name,i.name`,params)).rows;return {p,rows:rows.map(row=>({...row,diferenca:Number(row.meta)-Number(row.realizado),atingimento:Number(row.meta)?Number(row.realizado)/Number(row.meta)*100:0}))}; }
app.get('/api/reports/export.csv',auth,route(async(req,res)=>{const {p,rows}=await reportRows(req);res.attachment(`relatorio-${p.name}.csv`).type('text/csv').send(stringify(rows,{header:true}));}));
app.get('/api/reports/export.xlsx',auth,route(async(req,res)=>{const {p,rows}=await reportRows(req);const book=XLSX.utils.book_new();XLSX.utils.book_append_sheet(book,XLSX.utils.json_to_sheet(rows),'Relatório');const buffer=XLSX.write(book,{type:'buffer',bookType:'xlsx'});res.attachment(`relatorio-${p.name}.xlsx`).type('application/vnd.openxmlformats-officedocument.spreadsheetml.sheet').send(buffer);}));
app.get('/api/reports/export.pdf',auth,route(async(req,res)=>{const {p,rows}=await reportRows(req);res.setHeader('Content-Type','application/pdf');res.setHeader('Content-Disposition',`attachment; filename="relatorio-${p.name}.pdf"`);const doc=new PDFDocument({margin:40,size:'A4'});doc.pipe(res);doc.fontSize(18).fillColor('#172452').text('RV Digital — Relatório de Metas');doc.moveDown(.3).fontSize(10).fillColor('#64748b').text(`Período: ${p.name}`);doc.moveDown();doc.fillColor('#172452').fontSize(9).text('Vendedor',40,120).text('Mesa',175,120).text('Indicador',265,120).text('Meta',390,120).text('Realizado',455,120);let y=138;for(const row of rows.slice(0,42)){doc.fillColor('#243252').fontSize(8).text(row.vendedor,40,y,{width:125}).text(row.mesa||'-',175,y,{width:85}).text(row.indicador,265,y,{width:115}).text(Number(row.meta).toLocaleString('pt-BR'),390,y,{width:60,align:'right'}).text(Number(row.realizado).toLocaleString('pt-BR'),455,y,{width:70,align:'right'});y+=14;if(y>780){doc.addPage();y=50;}}doc.end();}));

app.use('/api',(_req,res)=>res.status(404).json({error:'Rota não encontrada.'}));
app.use((error,_req,res,_next)=>{console.error(error);if(error.code==='23505')return res.status(409).json({error:'Este registro já existe.'});res.status(error.status||500).json({error:error.message||'Erro interno do servidor.'});});
app.use((req,res)=>{const requested=decodeURIComponent(req.path==='/'?'/index.html':req.path);const candidate=path.resolve(root,`.${requested}`);const target=candidate.startsWith(root)&&fs.existsSync(candidate)&&fs.statSync(candidate).isFile()?candidate:path.join(root,'index.html');fs.readFile(target,(error,data)=>{if(error)return res.status(500).send('Execute npm run build antes de iniciar.');res.type(types[path.extname(target)]||'application/octet-stream').send(data);});});
app.listen(port,'0.0.0.0',()=>console.log(`RV Digital API disponível na porta ${port}`));
